/**
 * Simple Jobs API
 * This is a simple API for Job postings
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jordanyanke@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import JobItem from '../model/JobItem';

/**
* Developers service.
* @module api/DevelopersApi
* @version 1.0.0
*/
export default class DevelopersApi {

    /**
    * Constructs a new DevelopersApi. 
    * @alias module:api/DevelopersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getJob operation.
     * @callback module:api/DevelopersApi~getJobCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/JobItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * fetches a job
     * fetches a job by uuid 
     * @param {String} jobid pass an optional search string for looking up inventory
     * @param {module:api/DevelopersApi~getJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/JobItem>}
     */
    getJob(jobid, callback) {
      let postBody = null;

      // verify the required parameter 'jobid' is set
      if (jobid === undefined || jobid === null) {
        throw new Error("Missing the required parameter 'jobid' when calling getJob");
      }


      let pathParams = {
      };
      let queryParams = {
        'jobid': jobid
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [JobItem];

      return this.apiClient.callApi(
        '/job', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the searchJobs operation.
     * @callback module:api/DevelopersApi~searchJobsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/JobItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * searches jobs
     * By passing in the appropriate options, you can search for available jobs in the system 
     * @param {Object} opts Optional parameters
     * @param {String} opts.searchString pass an optional search string for looking up inventory
     * @param {Number} opts.skip number of records to skip for pagination
     * @param {Number} opts.limit maximum number of records to return
     * @param {module:api/DevelopersApi~searchJobsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/JobItem>}
     */
    searchJobs(opts, callback) {
      opts = opts || {};
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
        'searchString': opts['searchString'],
        'skip': opts['skip'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [JobItem];

      return this.apiClient.callApi(
        '/jobs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
